# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Jaap.WinWhisper
PackageVersion: 1.2.0
InstallerType: exe
InstallerSwitches:
  Silent: /s
Installers:
- InstallerUrl: https://github.com/GewoonJaap/WinWhisper/releases/download/V1.2.0/WinWhisperSetup.exe
  Architecture: x64
  InstallerSha256: 7C6552C2919C89B1ACCA59C20C78C0DA9C8418205B07CAF1A1F6B418D8A729FF
ManifestType: installer
ManifestVersion: 1.5.0
