# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Jaap.WinWhisper
PackageVersion: 1.2.0
PackageLocale: en-US
Publisher: GewoonJaap
PackageName: WinWhisper
License: MIT
Copyright: Copyright © 2023 Jaap
ShortDescription: WinWhisper, Subtitling Simplified
ManifestType: defaultLocale
ManifestVersion: 1.5.0
